rm *.dvi
rm *.aux
rm *.log
rm *.out
rm *.toc
rm *.bbl
rm *.blg
rm *.bcf
rm *.swo
rm *.swp
rm *.xml
#rm Thesis_main.pdf
rm Chapters/*/*.aux
rm Chapters/Others/*.aux
rm Chapters/ThesisSummary/*.aux
rm Chapters/ThesisSummary/*.bbl
rm Chapters/ThesisSummary/*.blg
rm Chapters/ThesisSummary/*.log
rm Chapters/Others/Appendices/*.aux
git status
